**NUMPY**

class name of numpy is ndarray

Numpy is a Python library used for working with arrays

In Python we have lists that serves the purpose of arrays,but they are

slow to process.

Numpy aims to provide an array object that is up to 50* faster than

traditional Python lists.

The array object in Numpy is called ndarray,it provides a lot of

supporting functions that make working with ndarray very easy

Arrays are very frequently used in data science,where speed and

resources are very important

Collection of homogenous data

It does not support hetrogenous data

size is fixed



In [ ]:
import numpy as np

In [ ]:
import numpy as np

x = np.ndarray([1,2,5,6])

print(x)

[[[[ 5.02353410e-310  0.00000000e+000  6.81355677e-310  5.02412233e-310
    -5.87532371e-192  6.81355661e-310]
   [ 5.02412233e-310 -6.25525140e-273  6.81356571e-310  6.81356619e-310
     3.08510398e+147  6.81356005e-310]
   [ 6.81355708e-310 -2.45956051e-074  6.81356571e-310  6.81355708e-310
     4.86839474e-039  6.81356571e-310]
   [ 6.81355708e-310  1.27774517e+151  6.81355646e-310  6.81356004e-310
    -2.34331521e-111  6.81355746e-310]
   [ 5.02412227e-310  1.42784972e-321  5.02412241e-310  6.81356739e-310
     6.81355706e-310  6.81355667e-310]]

  [[ 6.81355646e-310  6.81356711e-310  6.81355646e-310  6.81355662e-310
     6.81355667e-310  6.81355660e-310]
   [ 6.81355679e-310  6.81355662e-310  6.81355645e-310  6.81356634e-310
     6.81356703e-310  6.81355727e-310]
   [ 6.81356703e-310  6.81355667e-310  6.81355646e-310  6.81355662e-310
     6.81355667e-310  6.81355662e-310]
   [ 6.81355662e-310  6.81355667e-310  6.81355646e-310  6.81356712e-310
     6.81356712e-310  6.81355646e-310]

In [ ]:
import numpy as np

x = np.array([1,2,5,6])

print(x)

[1 2 5 6]


In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
print(x.ndim)

1


In [ ]:
print(x.shape)

(4,)


In [ ]:
import numpy as np

x = np.array([[1,2,5,6]])

print(x)
print(x.shape)
print(x.ndim)

[[1 2 5 6]]
(1, 4)
2


In [ ]:
import numpy as np

x = np.array([[1,2,5,6],[1,2,5,6]])

print(x)
print(x.shape)
print(x.ndim)

[[1 2 5 6]
 [1 2 5 6]]
(2, 4)
2


In [ ]:
(4,5)
(2,6)

(2, 6)

In [ ]:
(2,4,2)
(3,2,3)
(4,2,2)

(4, 2, 2)

In [ ]:


import numpy as np

x = np.array([[1,2,5,6],[1,2,5,6]])

print(x)
print(x.shape)
print(x.ndim)



[[1 2 5 6]
 [1 2 5 6]]
(2, 4)
2


In [ ]:

import numpy as np

x = np.array([1,2,5,6])

print(x)
print(x.shape)
print(x.ndim)


[1 2 5 6]
(4,)
1


In [ ]:
#1D single axis  - x
#2D two axis     - x,y
#3D three axis   - x,y,z

In [ ]:
x = np.array([[[2,4,5],[7,17,30]],[[2,4,5],[7,17,30]]])

print(x)
print(type(x))
print(x.ndim)
print(x.shape)

[[[ 2  4  5]
  [ 7 17 30]]

 [[ 2  4  5]
  [ 7 17 30]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)


In [ ]:
(2,4,2)
(3,2,3)
(4,2,2)

(4, 2, 2)

In [ ]:
import numpy as np

# Array of shape (4, 5) with specific values
array_1 = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]])

# Array of shape (2, 6) with specific values
array_2 = np.array([[21, 22, 23, 24, 25, 26],
                    [27, 28, 29, 30, 31, 32]])

print(array_1)
print(array_2)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[21 22 23 24 25 26]
 [27 28 29 30 31 32]]


In [ ]:
(2,4,2)
(3,2,3)
(4,2,2)

(4, 2, 2)

In [ ]:
import numpy as np

# Array of shape (2, 4, 2) with specific values
array_1 = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],
                    [[9, 10], [11, 12], [13, 14], [15, 16]]])

# Array of shape (3, 2, 3) with specific values
array_2 = np.array([[[17, 18, 19], [20, 21, 22]],
                    [[23, 24, 25], [26, 27, 28]],
                    [[29, 30, 31], [32, 33, 34]]])

# Array of shape (4, 2, 2) with specific values
array_3 = np.array([[[35, 36], [37, 38]],
                    [[39, 40], [41, 42]],
                    [[43, 44], [45, 46]],
                    [[47, 48], [49, 50]]])

print(array_1)
print(array_2)
print(array_3)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
[[[17 18 19]
  [20 21 22]]

 [[23 24 25]
  [26 27 28]]

 [[29 30 31]
  [32 33 34]]]
[[[35 36]
  [37 38]]

 [[39 40]
  [41 42]]

 [[43 44]
  [45 46]]

 [[47 48]
  [49 50]]]


In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.zeros((2,3,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
np.arange(20,80,5)

array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [ ]:
np.linspace(20,80,8)

array([20.        , 28.57142857, 37.14285714, 45.71428571, 54.28571429,
       62.85714286, 71.42857143, 80.        ])

In [ ]:
np.linspace(20,80)

array([20.        , 21.2244898 , 22.44897959, 23.67346939, 24.89795918,
       26.12244898, 27.34693878, 28.57142857, 29.79591837, 31.02040816,
       32.24489796, 33.46938776, 34.69387755, 35.91836735, 37.14285714,
       38.36734694, 39.59183673, 40.81632653, 42.04081633, 43.26530612,
       44.48979592, 45.71428571, 46.93877551, 48.16326531, 49.3877551 ,
       50.6122449 , 51.83673469, 53.06122449, 54.28571429, 55.51020408,
       56.73469388, 57.95918367, 59.18367347, 60.40816327, 61.63265306,
       62.85714286, 64.08163265, 65.30612245, 66.53061224, 67.75510204,
       68.97959184, 70.20408163, 71.42857143, 72.65306122, 73.87755102,
       75.10204082, 76.32653061, 77.55102041, 78.7755102 , 80.        ])

In [ ]:
np.full((3,4),70,dtype=float)

array([[70., 70., 70., 70.],
       [70., 70., 70., 70.],
       [70., 70., 70., 70.]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random((3,2,2))

array([[[0.95331192, 0.45170758],
        [0.63151509, 0.03667577]],

       [[0.25086354, 0.19545146],
        [0.79962367, 0.25523436]],

       [[0.94838005, 0.48490492],
        [0.87292668, 0.17792736]]])

In [ ]:
np.random.randint(100,200,(3,2,2))

array([[[100, 104],
        [131, 159]],

       [[154, 193],
        [170, 164]],

       [[132, 124],
        [145, 125]]])

In [ ]:
np.random.randint(100,size=(3,2,2))

array([[[96, 10],
        [84, 78]],

       [[86, 16],
        [53, 24]],

       [[83, 74],
        [96, 17]]])

In [ ]:
a = np.array([[1,2,7],[4,2,5]])

b = np.array([[1,2,7],[4,6,2]])

print(a)
print(b)
print(a.ndim)
print(b.ndim)

[[1 2 7]
 [4 2 5]]
[[1 2 7]
 [4 6 2]]
2
2


In [ ]:
#add

np.add(a,b)

array([[ 2,  4, 14],
       [ 8,  8,  7]])

In [ ]:
#subtract

np.subtract(a,b)

array([[ 0,  0,  0],
       [ 0, -4,  3]])

In [ ]:
np.multiply(a,b)

array([[ 1,  4, 49],
       [16, 12, 10]])

In [ ]:
#divide

np.divide(a,b)

array([[1.        , 1.        , 1.        ],
       [1.        , 0.33333333, 2.5       ]])

In [ ]:
np.power(a,b)

array([[     1,      4, 823543],
       [   256,     64,     25]])

In [ ]:
import numpy as np

a = np.array([[1,2,3,4,7],[3.5,2,4.9,5.1,9.0]])

print(a)

print(a.shape)

print(a.ndim)

y = np.floor(a)

print(y)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.9 5.1 9. ]]
(2, 5)
2
[[1. 2. 3. 4. 7.]
 [3. 2. 4. 5. 9.]]


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,7],[3.5,2,4.9,5.1,9.0]])

print(a)

print(a.shape)

y = np.ceil(a)

print(y)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.9 5.1 9. ]]
(2, 5)
[[1. 2. 3. 4. 7.]
 [4. 2. 5. 6. 9.]]


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,7],[3.5,2,4.9,5.1,9.0]])

print(a)

print(a.shape)

y = np.round(a)

print(y)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.9 5.1 9. ]]
(2, 5)
[[1. 2. 3. 4. 7.]
 [4. 2. 5. 5. 9.]]


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,7],[3.5,2,4.9,5.1,9.0]])

print(a)

print(a.shape)

y = np.rint(a)

print(y)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.9 5.1 9. ]]
(2, 5)
[[1. 2. 3. 4. 7.]
 [4. 2. 5. 5. 9.]]


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,7],[3.5,2,4.9,5.1,9.0]])

print(a)

print(type(a))

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.9 5.1 9. ]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,7],[3.5,2,4.9,5.1,9.0]])

print(a)

print(a.dtype)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.9 5.1 9. ]]
float64


In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[3.5,2,4.9,5.1,9.0]])

print(a)

print(a.dtype)

[['1' '2' '3' '4' '7']
 ['3.5' '2' '4.9' '5.1' '9.0']]
<U32


In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[3.5,2,4.9,5.1,9.0]])

x = a.astype(float)

print(x.dtype)

float64


In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[3.5,2,4.9,5.1,9.0]])

x = a.astype(complex)

print(x.dtype)

complex128


1 DIMENSIONAL SUBSETTING

In [ ]:
import numpy as np

a = np.array([1,2,'3',4,7])

print(a[2])

3


2 Dimensional Subset

In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[14,32,'30',40,77]])

print(a[1,1])

32


In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[14,32,'30',40,77]])

print(a[1,3])

40


In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[14,32,'30',40,77]])

print(a[0,3])

4


3D SUBSETTING

In [ ]:
import numpy as np

a = np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[13,25,'73',84,107],[14,32,'300',40,717]]])

print(a[1,0,4])

107


In [ ]:
print(a[0,1,4])

77


In [ ]:
print(a[1,0,0])

13


1D Slicing

In [ ]:
import numpy as np

a = np.array([1,2,'3',4,7])

print(a[1:4])

['2' '3' '4']


In [ ]:
import numpy as np

a = np.array([1,2,'3',4,7])

print(a[1:])

['2' '3' '4' '7']


In [ ]:
import numpy as np

a = np.array([1,2,'3',4,7])

print(a[:4])

['1' '2' '3' '4']


2d slicing

In [ ]:
import numpy as np
a = np.array([[1,2,'3',4,7],[14,32,'30',40,77]])

print(a.ndim)


#print(a)
print(a[0:2,2:5])   #0th and 1st row and 2nd 3rd 4th columns

print(a[:,1:3])     #0th and 1st row and 1st and 2nd columns

2
[['3' '4' '7']
 ['30' '40' '77']]
[['2' '3']
 ['32' '30']]


3D SLICING

In [ ]:
import numpy as np

a = np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]])

print(a[:,1,2:5])

[['30' '40' '77']
 ['320' '400' '770']]


In [ ]:
import numpy as np

a = np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]])

print(a[:,:,1:4])

[[['2' '3' '4']
  ['32' '30' '40']]

 [['72' '38' '94']
  ['392' '320' '400']]]


**Boolean Indexing**

In [ ]:
import numpy as np

a = np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]],dtype=int)

print(a)
print(a.ndim)
print(a.shape)

[[[  1   2   3   4   7]
  [ 14  32  30  40  77]]

 [[ 19  72  38  94  97]
  [ 15 392 320 400 770]]]
3
(2, 2, 5)


In [ ]:
b = a<100


print(b)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True False False False False]]]


Fancy Indexing

In [ ]:
import numpy as np

a = np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]],dtype=int)

print(a[0,0,3])

4


In [ ]:
import numpy as np

a = np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]],dtype=int)

print(a[[0],[0],[3]])

[4]


In [ ]:
import numpy as np

a = np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]],dtype=int)

print(a[[0,0,1],[0,1,0],[3,1,2]])

[ 4 32 38]


In [ ]:
import numpy as np

x = np.array([2,4,3,80,1])

x.sort()

print(x)

[ 1  2  3  4 80]


In [ ]:
import numpy as np

x = np.array([2,4,3,80,1])

y = np.sort(x)[::-1]

print(y)

[80  4  3  2  1]


In [ ]:
import numpy as np

x = np.array([[2,4,3,80,1],[4,14,1,8,10]])


x.sort()



print(x)


[[ 1  2  3  4 80]
 [ 1  4  8 10 14]]


In [ ]:
import numpy as np

x = np.array([[2,4,3,80,1],[4,14,1,8,10]])


x = np.sort(x,axis=1)

print(x)

[[ 1  2  3  4 80]
 [ 1  4  8 10 14]]


In [ ]:
import numpy as np

x = np.array([[2,4,3,80,1],[4,14,1,8,10]])


x = np.sort(x,axis=0)

print(x)

[[ 2  4  1  8  1]
 [ 4 14  3 80 10]]


In [ ]:
import numpy as np

x = np.array([[[2,4,3,80,1],[4,14,1,8,10]],[[20,94,2,8,1],[2,4,3,1,510]]])


x = np.sort(x,axis=0)

print(x)

[[[  2   4   2   8   1]
  [  2   4   1   1  10]]

 [[ 20  94   3  80   1]
  [  4  14   3   8 510]]]


In [ ]:
import numpy as np

x = np.array([[[2,4,3,80,1],[4,14,1,8,10]],[[20,94,2,8,1],[2,4,3,1,510]]])

print(x.ndim)
x = np.sort(x,axis=1)

print(x)

3
[[[  2   4   1   8   1]
  [  4  14   3  80  10]]

 [[  2   4   2   1   1]
  [ 20  94   3   8 510]]]


In [ ]:
#copy and view

import numpy as np

x = np.array([3,2,45,6,7,8])

y = x

z = x.copy()         #deep copy
w = x.view()         #shallow copy


print(w)
print(z)
print(y)
print(x)


x[2] = 405


print(w)
print(z)
print(y)
print(x)



[ 3  2 45  6  7  8]
[ 3  2 45  6  7  8]
[ 3  2 45  6  7  8]
[ 3  2 45  6  7  8]
[  3   2 405   6   7   8]
[ 3  2 45  6  7  8]
[  3   2 405   6   7   8]
[  3   2 405   6   7   8]


In [ ]:
#reshape,resize,flatten

import numpy as np

a = np.arange(16)

print(a)

print(a.shape)

b = a.reshape(2,8)

b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
b = a.reshape(4,4)

b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
import numpy as np

a = np.arange(16)

print(a)

print(a.shape)

b = a.reshape(4,5)

b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


ValueError: cannot reshape array of size 16 into shape (4,5)

In [ ]:
#reshape,resize,flatten

import numpy as np

a = np.arange(16)

print(a)

print(a.shape)

b = a.resize(4,10)

b
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [ ]:
import numpy as np

a = np.array([[2,3,4],[4,2,4]])

print(a)

b = a.flatten()

print(b)




[[2 3 4]
 [4 2 4]]
[2 3 4 4 2 4]


In [ ]:
#[3,4] - [2,6]

In [ ]:
import numpy as np

a = np.array([[2,3,4],[4,2,4]])

b = np.array([[2,3,4],[4,2,4],[4,2,4]])

print(a)

print('*' * 30)

print(b)

print('*' * 30)

print(np.dot(a,b))

[[2 3 4]
 [4 2 4]]
******************************
[[2 3 4]
 [4 2 4]
 [4 2 4]]
******************************
[[32 20 36]
 [32 24 40]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,2,4]],[[2,3,4],[4,2,4]]])

b = np.array([[[2,3,4],[4,2,4],[4,2,4]],[[2,3,4],[4,2,4],[4,2,4]]])

print(a)

print('*' * 30)

print(b)

print('*' * 30)

print(np.dot(a,b))

[[[2 3 4]
  [4 2 4]]

 [[2 3 4]
  [4 2 4]]]
******************************
[[[2 3 4]
  [4 2 4]
  [4 2 4]]

 [[2 3 4]
  [4 2 4]
  [4 2 4]]]
******************************
[[[[32 20 36]
   [32 20 36]]

  [[32 24 40]
   [32 24 40]]]


 [[[32 20 36]
   [32 20 36]]

  [[32 24 40]
   [32 24 40]]]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,2,4]],[[2,3,4],[4,2,4]]])


print(a)

print('*' * 30)

print(np.min(a))


[[[2 3 4]
  [4 2 4]]

 [[2 3 4]
  [4 2 4]]]
******************************
2


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4]],[[2,1,4],[4,0,4]]])


print(a)

print('*' * 30)

print(np.min(a))
print(np.min(a,axis=0))

[[[2 3 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]]]
******************************
0
[[2 1 4]
 [4 0 4]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4]],[[2,1,4],[4,0,4]]])


print(a)

print('*' * 30)

print(np.min(a))
print(np.min(a,axis=1))

[[[2 3 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]]]
******************************
0
[[2 1 4]
 [2 0 4]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4]],[[2,1,4],[4,0,4]]])


print(a)

print('*' * 30)

print(np.min(a))
print(np.min(a,axis=2))

[[[2 3 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]]]
******************************
0
[[2 1]
 [1 0]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4]],[[2,1,4],[4,0,4]]])


print(a)

print('*' * 30)

print(np.min(a))
print(np.max(a,axis=2))

[[[2 3 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]]]
******************************
0
[[4 4]
 [4 4]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4]],[[2,1,4],[4,0,4]]])


print(a)

print('*' * 30)

#print(np.min(a))
print(np.mean(a,axis=2))

[[[2 3 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]]]
******************************
[[3.         3.        ]
 [2.33333333 2.66666667]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4],[4,1,4]],[[2,1,4],[4,0,4],[4,1,4]]])

print(a)


[[[2 3 4]
  [4 1 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]
  [4 1 4]]]


ARRAY JOINING


In [1]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

c = np.vstack((a,b))

c

array([[ 3,  4,  2],
       [ 4,  5,  3],
       [ 4,  3,  1],
       [ 5, 32,  0]])

In [2]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

c = np.row_stack((a,b))

c

array([[ 3,  4,  2],
       [ 4,  5,  3],
       [ 4,  3,  1],
       [ 5, 32,  0]])

In [3]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

c = np.hstack((a,b))

c

array([[ 3,  4,  2,  4,  3,  1],
       [ 4,  5,  3,  5, 32,  0]])

In [4]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

c = np.column_stack((a,b))

c

array([[ 3,  4,  2,  4,  3,  1],
       [ 4,  5,  3,  5, 32,  0]])

In [5]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

x = np.concatenate((a,b))

x


array([[ 3,  4,  2],
       [ 4,  5,  3],
       [ 4,  3,  1],
       [ 5, 32,  0]])

In [7]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

x = np.concatenate((a,b),axis=1)

x


array([[ 3,  4,  2,  4,  3,  1],
       [ 4,  5,  3,  5, 32,  0]])